#!/usr/bin/env python3
"""Apply the generated Material palette to kitty, Firefox and VSCodium.

    apply-apps.py                  themes all three from the current colors.json
    apply-apps.py --only kitty     just one of them
    apply-apps.py --colors PATH    read a different palette

switchwall.sh calls this after qs-matugen writes colors.json, so a wallpaper
or mode change repaints the terminal, the browser and the editor along with
the bar.

Upstream does this in applycolor.sh, which cannot work here: it sed-s a
template with GNU `sed -i`, signals `pidof kitty`, writes escape sequences
into /dev/pts/* -- none of which exist on macOS -- and reads a
material_colors.scss that qs-matugen has never generated. This is the macOS
equivalent, driven straight off colors.json.
"""

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

CONFIG = Path.home() / ".config/quickshell"
STATE = Path.home() / "Library/Preferences/quickshell/State/user/generated"
COLORS = STATE / "colors.json"
MODE = STATE / "mode.txt"

KITTY_THEME = Path.home() / ".config/kitty/theme.conf"
KITTY_TEMPLATE = CONFIG / "scripts/colors/terminal/kitty-theme.conf"
SCHEME_BASE = CONFIG / "scripts/colors/terminal/scheme-base.json"

VSCODIUM = Path.home() / "Library/Application Support/VSCodium/User/settings.json"

FIREFOX = Path.home() / "Library/Application Support/Firefox"
# Written beside userChrome.css rather than into it: that file is hand-edited,
# and a generated file that overwrites hand-edits is a trap.
FF_SHEET = "userChrome-quickshell.css"
FF_IMPORT = f'@import "{FF_SHEET}";'
# firefox.cfg polls FF_SHEET and re-registers it through nsIStyleSheetService,
# which is what makes a colour change land without a restart. Only used to say
# so in the status line -- the stylesheet is written either way.
FF_AUTOCONFIG = Path("/Applications/Firefox.app/Contents/Resources/firefox.cfg")

BANNER = "Generated by scripts/colors/apply-apps.py -- edits are overwritten."


def camel(snake: str) -> str:
    head, *rest = snake.split("_")
    return head + "".join(w.capitalize() for w in rest)


def argb(hex_colour: str) -> int:
    v = hex_colour.lstrip("#")
    r, g, b = (int(v[i:i + 2], 16) for i in (0, 2, 4))
    return (255 << 24) | (r << 16) | (g << 8) | b


def to_hex(value: int) -> str:
    return "#{:02x}{:02x}{:02x}".format((value >> 16) & 0xFF, (value >> 8) & 0xFF, value & 0xFF)


def rgb(hex_colour: str) -> tuple:
    v = hex_colour.lstrip("#")
    return tuple(int(v[i:i + 2], 16) for i in (0, 2, 4))


def luminance(hex_colour: str) -> float:
    channels = []
    for c in (x / 255 for x in rgb(hex_colour)):
        channels.append(c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4)
    r, g, b = channels
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast(a: str, b: str) -> float:
    hi, lo = sorted((luminance(a), luminance(b)), reverse=True)
    return (hi + 0.05) / (lo + 0.05)


def readable(colour: str, background: str, target: float = 4.5) -> str:
    """Lift a colour until it is legible on background, keeping its hue.

    Material's on_* and *_container roles are *background* roles: on a dark
    surface they are dark. Slots that get used as prompt foreground therefore
    land at a contrast of about 2 and vanish. Blending toward white (or black
    on a light surface) keeps the hue and buys the contrast back.
    """
    if contrast(colour, background) >= target:
        return colour
    end = (255, 255, 255) if luminance(background) < 0.5 else (0, 0, 0)
    src = rgb(colour)
    for step in range(1, 21):
        t = step / 20
        mixed = "#{:02x}{:02x}{:02x}".format(*(round(a + (b - a) * t) for a, b in zip(src, end)))
        if contrast(mixed, background) >= target:
            return mixed
    return "#{:02x}{:02x}{:02x}".format(*end)


def terminal_colours(primary: str, dark: bool) -> dict:
    """The 16 ANSI colours, pulled toward the palette.

    Straight palette colours would make every ANSI slot a shade of the accent,
    so red stops reading as red. Harmonising a fixed base scheme instead keeps
    each slot recognisable while tinting it toward the theme -- the same trick
    upstream uses, via the same Material blend.
    """
    base = json.loads(SCHEME_BASE.read_text())["dark" if dark else "light"]
    try:
        from materialyoucolor.blend import Blend
    except ImportError:
        return base
    seed = argb(primary)
    return {name: to_hex(Blend.harmonize(argb(value), seed)) for name, value in base.items()}


def apply_kitty(colours: dict, dark: bool) -> str:
    if not KITTY_TEMPLATE.is_file():
        return "kitty: template missing, skipped"
    if not KITTY_THEME.parent.is_dir():
        return "kitty: not installed, skipped"

    values = {camel(k): v for k, v in colours.items()}
    values.update(terminal_colours(colours["primary"], dark))

    # The template writes each slot as `#$name #`; the leading '#' is literal,
    # so the placeholder is replaced by the bare hex digits.
    def replace(match):
        value = values.get(match.group(1))
        return value.lstrip("#") if value else match.group(0)

    body = re.sub(r"\$(\w+) #", replace, KITTY_TEMPLATE.read_text())

    # The template seeds the body from the ANSI base scheme, which leaves the
    # terminal a gruvbox grey next to a bar painted from the wallpaper. Take
    # the body straight from the palette instead, so the terminal background
    # IS the shell's background. kitty takes the last value for a key, so
    # these override the template above without editing it. The numbered ANSI
    # slots stay as they are -- they still need a red that reads as red.
    overrides = {
        "background": colours["surface"],
        "foreground": colours["on_surface"],
        "cursor": colours["primary"],
        "cursor_text_color": colours["on_primary"],
        "selection_background": colours["primary_container"],
        "selection_foreground": colours["on_primary_container"],
        "url_color": colours["primary"],
        "active_tab_background": colours["primary_container"],
        "active_tab_foreground": colours["on_primary_container"],
        "inactive_tab_background": colours["surface_container"],
        "inactive_tab_foreground": colours["on_surface_variant"],
        "tab_bar_background": colours["surface"],
        "active_border_color": colours["primary"],
        "inactive_border_color": colours["outline"],
    }
    body += "\n# Body colours, straight from the shell's palette.\n"
    body += "".join(f"{k:24}{v}\n" for k, v in overrides.items())

    # Slots 232-255 are prompt foreground -- starship writes `fg:245` for the
    # branch and the timing, `fg:243` for the arrow -- but the template fills
    # them from on_*/container roles, which are background roles and come out
    # near-black on a dark surface. Unlifted, colour245 sat at a contrast of
    # 2.1 against the background: the text was there and could not be read.
    # The 0-15 ANSI slots are deliberately left alone; those are a real colour
    # scheme, and a "black" that is not black is its own bug.
    background = overrides["background"]
    body = re.sub(
        r"^(color2[3-5]\d\s+)(#[0-9a-fA-F]{6})",
        lambda m: m.group(1) + readable(m.group(2), background),
        body,
        flags=re.M,
    )

    KITTY_THEME.write_text(f"# {BANNER}\n\n{body}")

    # kitty re-reads its config on SIGUSR1 -- no remote-control socket needed.
    reloaded = subprocess.run(["pkill", "-USR1", "-x", "kitty"], capture_output=True).returncode == 0
    return f"kitty: wrote {KITTY_THEME}" + (" and reloaded" if reloaded else " (not running)")


def firefox_profiles() -> list:
    """Every profile in profiles.ini, not just the default one.

    This used to follow [Install...] Default=, on the theory that it is the
    profile Firefox launches. With ShowSelector=1 that is not true -- the
    profile that launches is whichever one is picked at startup -- so theming
    only that one left the others painted in stock Firefox colours. Writing a
    stylesheet into each of them is cheaper than guessing.

    IsRelative=0 gives an absolute Path=; `FIREFOX / "/abs"` yields "/abs", so
    both forms fall out of the same join.
    """
    ini = FIREFOX / "profiles.ini"
    if not ini.is_file():
        return []
    paths = re.findall(r"^Path=(.+)$", ini.read_text(), re.M)
    return [d for d in (FIREFOX / p.strip() for p in paths) if d.is_dir()]


def apply_firefox(colours: dict, dark: bool) -> str:
    profiles = firefox_profiles()
    if not profiles:
        return "firefox: no profile found, skipped"

    css = firefox_css(colours, dark)
    for profile in profiles:
        chrome = profile / "chrome"
        chrome.mkdir(exist_ok=True)
        (chrome / FF_SHEET).write_text(css)

        # userChrome.css is the only file Firefox loads; ours has to be
        # imported from it, and @import must precede any rule in the file.
        user_chrome = chrome / "userChrome.css"
        existing = user_chrome.read_text() if user_chrome.is_file() else ""
        if FF_IMPORT not in existing:
            user_chrome.write_text(f"{FF_IMPORT}\n{existing}")

    live = FF_AUTOCONFIG.is_file() and FF_SHEET in FF_AUTOCONFIG.read_text()
    names = ", ".join(p.name for p in profiles)
    how = "live" if live else "restart Firefox to see it"
    return f"firefox: themed {len(profiles)} profile(s) [{names}] -- {how}"


def firefox_css(c: dict, dark: bool) -> str:
    """The chrome stylesheet, scoped to chrome documents.

    firefox.cfg registers this through nsIStyleSheetService as a USER_SHEET,
    and a user sheet applies to *every* document -- so an unscoped `:root` rule
    would push the shell's colour-scheme and variables onto every web page as
    well. @-moz-document is disabled for content stylesheets but still honoured
    in user sheets, which is exactly the case here; it is harmless on the
    userChrome.css import path, where the document is already a chrome one.
    """
    return f"""/* {BANNER} */

@-moz-document url-prefix("chrome://") {{

:root {{
  /* Chrome widgets Firefox draws itself -- scrollbars, dropdowns, checkboxes
     -- take their colours from this, not from the variables below. Without
     it they stay light on a dark toolbar. */
  color-scheme: {"dark" if dark else "light"};

  --qs-surface: {c['surface']};
  --qs-surface-container: {c['surface_container']};
  --qs-surface-high: {c['surface_container_high']};
  --qs-on-surface: {c['on_surface']};
  --qs-on-surface-variant: {c['on_surface_variant']};
  --qs-primary: {c['primary']};
  --qs-on-primary: {c['on_primary']};
  --qs-primary-container: {c['primary_container']};
  --qs-on-primary-container: {c['on_primary_container']};
  --qs-outline: {c['outline']};

  /* Firefox's own theme variables. Setting these covers the parts of the
     chrome that have no stable id to target. */
  --lwt-accent-color: var(--qs-surface) !important;
  --lwt-text-color: var(--qs-on-surface) !important;
  --toolbar-bgcolor: var(--qs-surface) !important;
  --toolbar-color: var(--qs-on-surface) !important;
  --toolbar-field-background-color: var(--qs-surface-container) !important;
  --toolbar-field-color: var(--qs-on-surface) !important;
  --toolbar-field-focus-background-color: var(--qs-surface-high) !important;
  --toolbar-field-focus-border-color: var(--qs-primary) !important;
  --tab-selected-bgcolor: var(--qs-primary-container) !important;
  --tab-selected-textcolor: var(--qs-on-primary-container) !important;
  --arrowpanel-background: var(--qs-surface-container) !important;
  --arrowpanel-color: var(--qs-on-surface) !important;
  --arrowpanel-border-color: var(--qs-outline) !important;
  --sidebar-background-color: var(--qs-surface) !important;
  --sidebar-text-color: var(--qs-on-surface) !important;
  --focus-outline-color: var(--qs-primary) !important;

  /* Text and icons. The block above is almost all surfaces; without these the
     labels and the toolbar glyphs keep their stock colour and disappear into
     the repainted chrome. */
  --lwt-tab-text: var(--qs-on-surface) !important;
  --lwt-toolbar-field-color: var(--qs-on-surface) !important;
  --lwt-toolbar-field-focus-color: var(--qs-on-surface) !important;
  --toolbar-field-focus-color: var(--qs-on-surface) !important;
  --toolbarbutton-icon-fill: var(--qs-on-surface) !important;
  --toolbarbutton-icon-fill-attention: var(--qs-primary) !important;
  --toolbarbutton-hover-background: var(--qs-surface-high) !important;
  --panel-description-color: var(--qs-on-surface-variant) !important;
  --urlbar-box-text-color: var(--qs-on-surface) !important;
}}

/* The chrome itself. One surface behind the whole toolbox, with the
   individual toolbars transparent on top of it, so there are no seams. */
#navigator-toolbox {{
  background: var(--qs-surface) !important;
  border-bottom: 1px solid var(--qs-outline) !important;
}}
#TabsToolbar, #nav-bar, #PersonalToolbar, #titlebar {{
  background: transparent !important;
  color: var(--qs-on-surface) !important;
}}

#urlbar-background, #searchbar {{
  background: var(--qs-surface-container) !important;
  border-color: var(--qs-outline) !important;
}}
#urlbar[focused="true"] > #urlbar-background {{
  background: var(--qs-surface-high) !important;
  border-color: var(--qs-primary) !important;
}}
#urlbar-input, #searchbar .searchbar-textbox {{ color: var(--qs-on-surface) !important; }}
#urlbar-input::placeholder {{ color: var(--qs-on-surface-variant) !important; }}

/* Tab labels. .tab-content[selected] below only covers the selected tab; the
   rest inherit whatever the stock theme had and go unreadable. */
.tab-label {{ color: var(--qs-on-surface) !important; }}
.tabbrowser-tab:not([selected]) .tab-label {{ color: var(--qs-on-surface-variant) !important; }}
toolbarbutton, .toolbarbutton-text, #urlbar .urlbar-icon {{
  color: var(--qs-on-surface) !important;
  fill: var(--qs-on-surface) !important;
}}

.tab-background[selected] {{ background: var(--qs-primary-container) !important; }}
.tab-content[selected] {{ color: var(--qs-on-primary-container) !important; }}
.tabbrowser-tab:not([selected]):hover .tab-background {{
  background: var(--qs-surface-container) !important;
}}

/* Menus, panels and the findbar, which do not inherit the toolbar colours. */
menupopup, panel, .panel-arrowcontent, #findbar {{
  background-color: var(--qs-surface-container) !important;
  color: var(--qs-on-surface) !important;
}}
menuitem:hover, menu:hover, toolbarbutton:hover {{
  background-color: var(--qs-primary-container) !important;
  color: var(--qs-on-primary-container) !important;
}}

}}
"""


def apply_vscodium(colours: dict, dark: bool) -> str:
    """Repaint VSCodium through workbench.colorCustomizations.

    No generated theme extension and no restart: settings.json is the native
    override channel and VSCodium re-reads it on write, so the editor repaints
    with the wallpaper like the bar does. Only our own key is replaced -- the
    rest of settings.json is hand-written and is left exactly as it was.
    """
    if not VSCODIUM.parent.is_dir():
        return "vscodium: not installed, skipped"

    settings = {}
    if VSCODIUM.is_file():
        try:
            settings = json.loads(VSCODIUM.read_text())
        except json.JSONDecodeError as exc:
            # Comments are legal in VS Code's settings.json and json refuses
            # them. Bailing out beats writing over a file we cannot read.
            return f"vscodium: settings.json is not plain JSON ({exc}), skipped"

    settings["workbench.colorCustomizations"] = vscodium_colours(colours, dark)
    VSCODIUM.write_text(json.dumps(settings, indent=4) + "\n")
    return f"vscodium: wrote {VSCODIUM}"


def vscodium_colours(c: dict, dark: bool) -> dict:
    """Palette roles mapped onto the editor's colour ids.

    Every foreground here is the on_* role that Material pairs with the
    surface behind it, so the contrast comes from the palette rather than from
    a guess -- the failure that made the terminal unreadable was pairing an
    on_* role with a surface it was never meant to sit on.
    """
    term = terminal_colours(c["primary"], dark)
    ansi = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"]
    colours = {
        "editor.background": c["surface"],
        "editor.foreground": c["on_surface"],
        "editorCursor.foreground": c["primary"],
        "editor.selectionBackground": c["primary_container"],
        "editor.lineHighlightBackground": c["surface_container_low"],
        "editorLineNumber.foreground": c["outline"],
        "editorLineNumber.activeForeground": c["primary"],
        "editorWidget.background": c["surface_container"],
        "editorWidget.foreground": c["on_surface"],
        "editorWidget.border": c["outline"],
        "editorGroupHeader.tabsBackground": c["surface_container"],
        "editorGroup.border": c["outline_variant"],

        "activityBar.background": c["surface_container"],
        "activityBar.foreground": c["on_surface"],
        "activityBar.inactiveForeground": c["on_surface_variant"],
        "activityBar.border": c["outline_variant"],
        "activityBarBadge.background": c["primary"],
        "activityBarBadge.foreground": c["on_primary"],

        "sideBar.background": c["surface_container"],
        "sideBar.foreground": c["on_surface"],
        "sideBar.border": c["outline_variant"],
        "sideBarTitle.foreground": c["on_surface_variant"],
        "sideBarSectionHeader.background": c["surface_container_high"],
        "sideBarSectionHeader.foreground": c["on_surface"],

        "titleBar.activeBackground": c["surface_container"],
        "titleBar.activeForeground": c["on_surface"],
        "titleBar.inactiveBackground": c["surface"],
        "titleBar.inactiveForeground": c["on_surface_variant"],
        "titleBar.border": c["outline_variant"],

        "statusBar.background": c["primary_container"],
        "statusBar.foreground": c["on_primary_container"],
        "statusBar.border": c["outline_variant"],
        "statusBar.noFolderBackground": c["surface_container"],
        "statusBar.noFolderForeground": c["on_surface"],
        "statusBarItem.remoteBackground": c["primary"],
        "statusBarItem.remoteForeground": c["on_primary"],

        "tab.activeBackground": c["surface"],
        "tab.activeForeground": c["on_surface"],
        "tab.activeBorderTop": c["primary"],
        "tab.inactiveBackground": c["surface_container"],
        "tab.inactiveForeground": c["on_surface_variant"],
        "tab.border": c["outline_variant"],

        "panel.background": c["surface"],
        "panel.border": c["outline_variant"],
        "panelTitle.activeForeground": c["on_surface"],
        "panelTitle.inactiveForeground": c["on_surface_variant"],

        "terminal.background": c["surface"],
        "terminal.foreground": c["on_surface"],
        "terminalCursor.foreground": c["primary"],
        "terminal.selectionBackground": c["primary_container"],

        "list.activeSelectionBackground": c["primary_container"],
        "list.activeSelectionForeground": c["on_primary_container"],
        "list.inactiveSelectionBackground": c["surface_container_high"],
        "list.inactiveSelectionForeground": c["on_surface"],
        "list.hoverBackground": c["surface_container_high"],
        "list.hoverForeground": c["on_surface"],
        "list.highlightForeground": c["primary"],

        "input.background": c["surface_container_high"],
        "input.foreground": c["on_surface"],
        "input.border": c["outline"],
        "input.placeholderForeground": c["on_surface_variant"],
        "dropdown.background": c["surface_container_high"],
        "dropdown.foreground": c["on_surface"],
        "dropdown.border": c["outline"],

        "button.background": c["primary"],
        "button.foreground": c["on_primary"],
        "button.hoverBackground": c["primary_dim"],
        "badge.background": c["primary"],
        "badge.foreground": c["on_primary"],
        "focusBorder": c["primary"],

        "quickInput.background": c["surface_container"],
        "quickInput.foreground": c["on_surface"],
        "menu.background": c["surface_container"],
        "menu.foreground": c["on_surface"],
        "menu.selectionBackground": c["primary_container"],
        "menu.selectionForeground": c["on_primary_container"],
        "menu.border": c["outline"],

        "notifications.background": c["surface_container"],
        "notifications.foreground": c["on_surface"],
        "notifications.border": c["outline"],

        "editorError.foreground": c["error"],
        "editorWarning.foreground": c["on_error_container"],
        "editorInfo.foreground": c["primary"],
        "widget.border": c["outline_variant"],
        "scrollbarSlider.background": c["surface_container_highest"],
        "scrollbarSlider.hoverBackground": c["outline_variant"],
        "scrollbarSlider.activeBackground": c["outline"],
    }
    # The integrated terminal gets the same harmonised ANSI scheme kitty uses,
    # so a shell looks the same in either place.
    for i, name in enumerate(ansi):
        colours[f"terminal.ansi{name.capitalize()}"] = term[f"term{i}"]
        colours[f"terminal.ansiBright{name.capitalize()}"] = term[f"term{i + 8}"]
    return colours


def self_check() -> int:
    """apply-apps.py --self-check -- the contrast lift, which is the only
    part here with arithmetic to get wrong."""
    dark, light = "#0a0f0e", "#f6faf8"

    # Known-good values are returned untouched.
    assert readable("#dde8e4", dark) == "#dde8e4"

    # The regression this fixes: outline_variant in a prompt foreground slot.
    assert contrast("#404a47", dark) < 3
    assert contrast(readable("#404a47", dark), dark) >= 4.5

    # Every on_*/container role clears the floor, on either surface, and a
    # lift never overshoots past the end of the ramp.
    for role in ("#12483f", "#27403b", "#285b51", "#871f21", "#490006", "#2c453f"):
        for bg in (dark, light):
            assert contrast(readable(role, bg), bg) >= 4.5, (role, bg)

    # A lift goes toward white on a dark surface and toward black on a light
    # one -- the direction is what makes it readable rather than merely
    # different.
    assert luminance(readable("#12483f", dark)) > luminance("#12483f")
    assert luminance(readable("#d5f3ff", light)) < luminance("#d5f3ff")

    # Black on black is the worst case and still has to come out legible.
    assert contrast(readable("#000000", "#000000"), "#000000") >= 4.5

    print("self-check ok")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--colors", default=str(COLORS))
    ap.add_argument("--only", choices=["kitty", "firefox", "vscodium"])
    ap.add_argument("--self-check", action="store_true", help=argparse.SUPPRESS)
    args = ap.parse_args()

    if args.self_check:
        return self_check()

    path = Path(args.colors)
    if not path.is_file():
        print(f"apply-apps: no palette at {path}", file=sys.stderr)
        return 1
    colours = json.loads(path.read_text())
    dark = MODE.read_text().strip() == "dark" if MODE.is_file() else True

    for name, fn in (("kitty", lambda: apply_kitty(colours, dark)),
                     ("firefox", lambda: apply_firefox(colours, dark)),
                     ("vscodium", lambda: apply_vscodium(colours, dark))):
        if args.only in (None, name):
            print(fn())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
