#!/usr/bin/env python3
"""Apply the generated Material palette to kitty and Firefox.

    apply-apps.py                  themes both from the current colors.json
    apply-apps.py --only kitty     just one of them
    apply-apps.py --colors PATH    read a different palette

switchwall.sh calls this after qs-matugen writes colors.json, so a wallpaper
or mode change repaints the terminal and the browser along with the bar.

Upstream does this in applycolor.sh, which cannot work here: it sed-s a
template with GNU `sed -i`, signals `pidof kitty`, writes escape sequences
into /dev/pts/* -- none of which exist on macOS -- and reads a
material_colors.scss that qs-matugen has never generated. This is the macOS
equivalent, driven straight off colors.json.
"""

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

CONFIG = Path.home() / ".config/quickshell"
STATE = Path.home() / "Library/Preferences/quickshell/State/user/generated"
COLORS = STATE / "colors.json"
MODE = STATE / "mode.txt"

KITTY_THEME = Path.home() / ".config/kitty/theme.conf"
KITTY_TEMPLATE = CONFIG / "scripts/colors/terminal/kitty-theme.conf"
SCHEME_BASE = CONFIG / "scripts/colors/terminal/scheme-base.json"

FIREFOX = Path.home() / "Library/Application Support/Firefox"
# Written beside userChrome.css rather than into it: that file is hand-edited,
# and a generated file that overwrites hand-edits is a trap.
FF_SHEET = "userChrome-quickshell.css"
FF_IMPORT = f'@import "{FF_SHEET}";'

BANNER = "Generated by scripts/colors/apply-apps.py -- edits are overwritten."


def camel(snake: str) -> str:
    head, *rest = snake.split("_")
    return head + "".join(w.capitalize() for w in rest)


def argb(hex_colour: str) -> int:
    v = hex_colour.lstrip("#")
    r, g, b = (int(v[i:i + 2], 16) for i in (0, 2, 4))
    return (255 << 24) | (r << 16) | (g << 8) | b


def to_hex(value: int) -> str:
    return "#{:02x}{:02x}{:02x}".format((value >> 16) & 0xFF, (value >> 8) & 0xFF, value & 0xFF)


def terminal_colours(primary: str, dark: bool) -> dict:
    """The 16 ANSI colours, pulled toward the palette.

    Straight palette colours would make every ANSI slot a shade of the accent,
    so red stops reading as red. Harmonising a fixed base scheme instead keeps
    each slot recognisable while tinting it toward the theme -- the same trick
    upstream uses, via the same Material blend.
    """
    base = json.loads(SCHEME_BASE.read_text())["dark" if dark else "light"]
    try:
        from materialyoucolor.blend import Blend
    except ImportError:
        return base
    seed = argb(primary)
    return {name: to_hex(Blend.harmonize(argb(value), seed)) for name, value in base.items()}


def apply_kitty(colours: dict, dark: bool) -> str:
    if not KITTY_TEMPLATE.is_file():
        return "kitty: template missing, skipped"
    if not KITTY_THEME.parent.is_dir():
        return "kitty: not installed, skipped"

    values = {camel(k): v for k, v in colours.items()}
    values.update(terminal_colours(colours["primary"], dark))

    # The template writes each slot as `#$name #`; the leading '#' is literal,
    # so the placeholder is replaced by the bare hex digits.
    def replace(match):
        value = values.get(match.group(1))
        return value.lstrip("#") if value else match.group(0)

    body = re.sub(r"\$(\w+) #", replace, KITTY_TEMPLATE.read_text())

    # The template seeds the body from the ANSI base scheme, which leaves the
    # terminal a gruvbox grey next to a bar painted from the wallpaper. Take
    # the body straight from the palette instead, so the terminal background
    # IS the shell's background. kitty takes the last value for a key, so
    # these override the template above without editing it. The numbered ANSI
    # slots stay as they are -- they still need a red that reads as red.
    overrides = {
        "background": colours["surface"],
        "foreground": colours["on_surface"],
        "cursor": colours["primary"],
        "cursor_text_color": colours["on_primary"],
        "selection_background": colours["primary_container"],
        "selection_foreground": colours["on_primary_container"],
        "url_color": colours["primary"],
        "active_tab_background": colours["primary_container"],
        "active_tab_foreground": colours["on_primary_container"],
        "inactive_tab_background": colours["surface_container"],
        "inactive_tab_foreground": colours["on_surface_variant"],
        "tab_bar_background": colours["surface"],
        "active_border_color": colours["primary"],
        "inactive_border_color": colours["outline"],
    }
    body += "\n# Body colours, straight from the shell's palette.\n"
    body += "".join(f"{k:24}{v}\n" for k, v in overrides.items())

    KITTY_THEME.write_text(f"# {BANNER}\n\n{body}")

    # kitty re-reads its config on SIGUSR1 -- no remote-control socket needed.
    reloaded = subprocess.run(["pkill", "-USR1", "-x", "kitty"], capture_output=True).returncode == 0
    return f"kitty: wrote {KITTY_THEME}" + (" and reloaded" if reloaded else " (not running)")


def firefox_profile() -> Path | None:
    ini = FIREFOX / "profiles.ini"
    if not ini.is_file():
        return None
    # [Install...] Default= is the profile Firefox actually launches, which is
    # not always the one flagged Default=1 in the [Profile...] sections.
    install = re.search(r"^\[Install[^\]]*\]\s*\nDefault=(.+)$", ini.read_text(), re.M)
    if not install:
        return None
    profile = FIREFOX / install.group(1).strip()
    return profile if profile.is_dir() else None


def apply_firefox(colours: dict) -> str:
    profile = firefox_profile()
    if profile is None:
        return "firefox: no profile found, skipped"

    chrome = profile / "chrome"
    chrome.mkdir(exist_ok=True)
    (chrome / FF_SHEET).write_text(firefox_css(colours))

    # userChrome.css is the only file Firefox loads; ours has to be imported
    # from it, and @import must precede any rule in the file.
    user_chrome = chrome / "userChrome.css"
    existing = user_chrome.read_text() if user_chrome.is_file() else ""
    if FF_IMPORT not in existing:
        user_chrome.write_text(f"{FF_IMPORT}\n{existing}")
        note = "imported from userChrome.css"
    else:
        note = "already imported"
    return f"firefox: wrote {chrome / FF_SHEET} ({note}) -- restart Firefox to see it"


def firefox_css(c: dict) -> str:
    return f"""/* {BANNER} */

:root {{
  --qs-surface: {c['surface']};
  --qs-surface-container: {c['surface_container']};
  --qs-surface-high: {c['surface_container_high']};
  --qs-on-surface: {c['on_surface']};
  --qs-on-surface-variant: {c['on_surface_variant']};
  --qs-primary: {c['primary']};
  --qs-on-primary: {c['on_primary']};
  --qs-primary-container: {c['primary_container']};
  --qs-on-primary-container: {c['on_primary_container']};
  --qs-outline: {c['outline']};

  /* Firefox's own theme variables. Setting these covers the parts of the
     chrome that have no stable id to target. */
  --lwt-accent-color: var(--qs-surface) !important;
  --lwt-text-color: var(--qs-on-surface) !important;
  --toolbar-bgcolor: var(--qs-surface) !important;
  --toolbar-color: var(--qs-on-surface) !important;
  --toolbar-field-background-color: var(--qs-surface-container) !important;
  --toolbar-field-color: var(--qs-on-surface) !important;
  --toolbar-field-focus-background-color: var(--qs-surface-high) !important;
  --toolbar-field-focus-border-color: var(--qs-primary) !important;
  --tab-selected-bgcolor: var(--qs-primary-container) !important;
  --tab-selected-textcolor: var(--qs-on-primary-container) !important;
  --arrowpanel-background: var(--qs-surface-container) !important;
  --arrowpanel-color: var(--qs-on-surface) !important;
  --arrowpanel-border-color: var(--qs-outline) !important;
  --sidebar-background-color: var(--qs-surface) !important;
  --sidebar-text-color: var(--qs-on-surface) !important;
  --focus-outline-color: var(--qs-primary) !important;
}}

/* The chrome itself. One surface behind the whole toolbox, with the
   individual toolbars transparent on top of it, so there are no seams. */
#navigator-toolbox {{
  background: var(--qs-surface) !important;
  border-bottom: 1px solid var(--qs-outline) !important;
}}
#TabsToolbar, #nav-bar, #PersonalToolbar, #titlebar {{
  background: transparent !important;
  color: var(--qs-on-surface) !important;
}}

#urlbar-background, #searchbar {{
  background: var(--qs-surface-container) !important;
  border-color: var(--qs-outline) !important;
}}
#urlbar[focused="true"] > #urlbar-background {{
  background: var(--qs-surface-high) !important;
  border-color: var(--qs-primary) !important;
}}
#urlbar-input, #urlbar-input::placeholder {{ color: var(--qs-on-surface) !important; }}

.tab-background[selected] {{ background: var(--qs-primary-container) !important; }}
.tab-content[selected] {{ color: var(--qs-on-primary-container) !important; }}
.tabbrowser-tab:not([selected]):hover .tab-background {{
  background: var(--qs-surface-container) !important;
}}

/* Menus, panels and the findbar, which do not inherit the toolbar colours. */
menupopup, panel, .panel-arrowcontent, #findbar {{
  background-color: var(--qs-surface-container) !important;
  color: var(--qs-on-surface) !important;
}}
menuitem:hover, menu:hover, toolbarbutton:hover {{
  background-color: var(--qs-primary-container) !important;
  color: var(--qs-on-primary-container) !important;
}}
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--colors", default=str(COLORS))
    ap.add_argument("--only", choices=["kitty", "firefox"])
    args = ap.parse_args()

    path = Path(args.colors)
    if not path.is_file():
        print(f"apply-apps: no palette at {path}", file=sys.stderr)
        return 1
    colours = json.loads(path.read_text())
    dark = MODE.read_text().strip() == "dark" if MODE.is_file() else True

    for name, fn in (("kitty", lambda: apply_kitty(colours, dark)),
                     ("firefox", lambda: apply_firefox(colours))):
        if args.only in (None, name):
            print(fn())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
