#!/usr/bin/env lua
package.cpath = package.cpath .. ";" .. os.getenv("HOME") .. "/.local/share/sketchybar_lua/?.so"
package.path = package.path .. ";" .. os.getenv("HOME") .. "/.config/sketchybar/?.lua"
require("init")
